# Generated by Django 2.1.3 on 2018-11-17 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_meetingnotes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MeetingNotes',
            new_name='MeetingNote',
        ),
    ]
